version: "3.4"

networks:
  iexec-blockchain-net:
    external: true

services:

  chain:
    image: nexus.iex.ec/poco-chain:token-v5.1.0
    container_name: chain
    ports:
      - 8545:8545
    networks:
      - iexec-blockchain-net

  broker:
    image: iexec-broker
    container_name: broker
    environment:
      - CHAIN: 'http://chain:8545'
      - PROXY: '0xBF6B2B07e47326B7c8bfCb4A5460bef9f0Fd2002'
      - MNEMONIC: ${BROKER_PRIVATE_KEY} #must use an other wallet for the broker, like wallet-abc
      - PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - chain
    networks:
      - iexec-blockchain-net

  blockchain-adapter-mongo:
    image: library/mongo:4.4
    container_name: blockchain-adapter-mongo
    entrypoint: "/bin/bash"
    command: -c "mongod --bind_ip_all --port 13012"
    ports:
      - 13012:13012
    networks:
      - iexec-blockchain-net