services:

  ibaa-chain:
    image: docker-regis.iex.ec/poco-chain:native-v5.4.2-5s
    expose:
      - "8545"

  ibaa-blockchain-adapter-mongo:
    image: library/mongo:4.4
    entrypoint: "/bin/bash"
    command: -c "mongod --bind_ip_all --port 13012"
