chain:
  id: ${IEXEC_ADAPTER_API_CHAIN_ID:133}
  node-address: ${IEXEC_ADAPTER_API_NODE_ADDRESS:https://viviani.iex.ec/}
  hub-address: ${IEXEC_ADAPTER_API_HUB_ADDRESS:0x3eca1B216A7DF1C7689aEb259fFB83ADFB894E7f}
  pool-address: ${IEXEC_ADAPTER_API_POOL_ADDRESS:0xd698cABf5F8d5DDf174Bb69D40De98cCE8AAA7Da}
  is-sidechain: ${IEXEC_ADAPTER_API_IS_SIDECHAIN:true}

wallet:
  path: ${IEXEC_ADAPTER_API_WALLET_PATH:src/main/resources/wallet.json}
  password: ${IEXEC_ADAPTER_API_WALLET_PASSWORD:whatever}